### PR TITLE
Value functions

### PR DESCRIPTION
**Pull request by ComLock**
These might be useful...

Have not actually run this code yet. Perhaps some tests would be good?

### CODE REVIEW

**Comment by ComLock** [comment]
Note: I did a rebase origin/master and force push of this branch since toStr was merged already :)

**Comment by torlokken** [comment]
Thanks, yes we need to add some tests for this lib soon.  Added to my list.

**Comment by ComLock** [comment]
@torlokken Added some tests, driven by mocha. Used yarn, instead of npm, in order to lock the versions.

**Comment by Bellfalasch** [comment]
Could you revisit this CWE and see if it is still useful? It looks very nice, I like that we add more functions for handling values. But this PR is old. Check it and see if any changes are needed, then update this PR or create a new and notify me.

**Pull request merged**
