### PR TITLE
First version of hasProperty function

### PR DESCRIPTION
**Pull request by odadoda**

### CODE REVIEW

**Comment by Bellfalasch** [comment]
I just got this code in another project related to a similar functionality, using the "filter"-function in JavaScript. Could it be used instead?

```
function findValueInJson(json, paths) {
	var hits = paths.filter(function(path) { return json.data[path]; })
	return hits.length ? hits[0] : false;
}
```

**Comment by odadoda** [comment]
This code assume the paths you are getting is in the "data" property. That may not always be the case. I'll take a closer look at it and see how it work and how I can modify it.

**Comment by enonicnorway** [comment]
True, that might not be good enough. Should handle infinite depths.

I've never used filter before, liked the idea though.

**Comment by Bellfalasch** [comment]
Could you revisit this CWE? When you have time.

Not sure if ODA's solution works. What we want is to not need to do all code for json like this:

`if (data && data.subnode && data.subnode.myitem) {`

Right now, if we don't do this, if .subnode is not there the call for `.subnode.myitem` will crash.
We need a function that just takes any JS object annotated string like "data.subnode.myitem.value.fisk.bil" and basically makes sure to return true if it exists or false if it doesn't, so extracting deep nested data is easier.

Most likely best with new pull request for it.

**Comment by cfenzo** [comment]
Is this something that could be solved with something like [developit's dlv function](https://github.com/developit/dlv) ?

> Safely get a dot-notated path within a nested object, with ability to return a default if the full key path does not exist or the value is undefined
```js
import delve from 'dlv';

let obj = {
	a: {
		b: {
			c: 1
			d: undefined
			e: null
		}
	}
};

//use string dot notation for keys
delve(obj, 'a.b.c') === 1;

//or use an array key
delve(obj, ['a', 'b', 'c']) === 1;

delve(obj, 'a.b') === obj.a.b;

//returns undefined if the full key path does not exist and no default is specified
delve(obj, 'a.b.c.f') === undefined;

//optional third parameter for default if the full key in path is missing
delve(obj, 'a.b.c.f', 'foo') === 'foo';

//or if the key exists but the value is undefined
delve(obj, 'a.b.c.d', 'foo') === 'foo';

//Non-truthy defined values are still returned if they exist at the full keypath
delve(obj, 'a.b.c.e', 'foo') === null;

//undefined obj or key returns undefined, unless a default is supplied
delve(undefined, 'a.b.c') === undefined;
delve(undefined, 'a.b.c', 'foo') === 'foo';
delve(obj, undefined, 'foo') === 'foo';
```

It's only 128b
```js
export default function dlv(obj, key, def, p) {
	p = 0;
	key = key.split ? key.split('.') : key;
	while (obj && p<key.length) obj = obj[key[p++]];
	return obj===undefined ? def : obj;
}
```

**Comment by ComLock** [comment]
Fixed by https://github.com/enonic/lib-util/pull/25

**Pull request closed without merging**
